var {model,Schema}=require('mongoose');
const ProfileSchema=new Schema({
    user:{
        //关联数据表
        type:String,
        ref:'users',
        required:true
    },
    handle:{
        type:String,
        required:true,
        max:40
    },
    website:{
        type:String
    },
    location:{
        type:String
    },
    status:{  //职位
        type:String,
        required:true
    },
    skills:{  
        type:[String],
        required:true
    },
    bio:{ //简介
        type:String
    },
    githubusername:{
        type:String
    },
    experience:[
        {
            current:{
                type:Boolean,
                default:true
            },
            title:{
                type:String,
                require:true
            },
            company:{
                type:String,
            },
            location:{
                type:String,
                require:true
            }, 
            from:{
                type:Date,
                required:true
            },
            to:{
                type:String
            },
            description:{
                type:String
            }
        }
    ],
    education:[
        {
            current:{
                type:Boolean,
                default:true
            },
            school:{
                type:String,
                required:true
            },
            degree:{ //学位
                type:String,
                required:true
            },
            fieldofstudy:{ //专业
                type:String
            }, 
            from:{
                type:Date,
                required:true
            },
            to:{
                type:String
            },
            description:{
                type:String
            }
        }
    ],
    social:{
        //社交
        webchat:{
            type:String
        },
        qq:{
            type:String
        }
    },
    date:{
        type:Date,
        default:Date.now
    }
});
module.exports=Profile=model('profile',ProfileSchema);